### ISSUE TITLE
Caused by: java.lang.NoSuchFieldException: modifiers

### ISSUE THREAD

**Issue by RemineHD** [InventivetalentDev/ReflectionHelper#55]
[18:04:49 WARN]: Caused by: java.lang.NoSuchFieldException: modifiers

[18:04:49 WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2610)

[18:04:49 WARN]: 	at org.inventivetalent.reflection.util.AccessUtil.setAccessible(AccessUtil.java:21)

[18:04:49 WARN]: 	at org.inventivetalent.reflection.resolver.FieldResolver.resolveByLastType(FieldResolver.java:147)

[18:04:49 WARN]: 	at org.inventivetalent.reflection.minecraft.DataWatcher$V1_8.setValue(DataWatcher.java:394)

[18:04:49 WARN]: 	at org.inventivetalent.reflection.minecraft.DataWatcher.setValue(DataWatcher.java:41)

[18:04:49 WARN]: 	at org.inventivetalent.reflection.minecraft.DataWatcher.setValue(DataWatcher.java:48)

[18:04:49 WARN]: 	at es.zaroz.core.BossBar.EntityBossBar.updateDataWatcher(EntityBossBar.java:194)

[18:04:49 WARN]: 	... 25 more

**Comment by PikaMug** [comment]
Also having this issue, Version is v1_8_R3 (10803)
